name: create docker image from workflow
env:
  versionid: 2.0.1
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: maven build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: change jar version when package
        run: |
          sed 's/0.0.1-SNAPSHOT/${{env.versionid}}/g' pom.xml > pom_new.xml
          cat pom_new.xml
      - name: setup jdk11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: maven build jar
        run: mvn -B clean package -DskipTests
      - name: Maven verify
        run: mvn -B clean verify
  docker:
    runs-on: ubuntu-latest
    name: docker build and push
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: docker build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: adamcao/hellospringmvc:${{env.versionid}}
          build-args: TAGVERSION=${{env.versionid}}

      - name: image digest
        run: |
          echo ${{steps.docker_build.outputs.digest}}
