name: create docker image from workflow
on:
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    name: docker build and push
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: setup jdk11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: maven build jar
        run: mvn -B clean package -DskipTests
      - name: docker build
        run: |
          docker build -t adamcao/hellospringmvc:1.0 .
      - name: docker login
        run: |
          docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}
      - name: docker push
        run: |
          docker push adamcao/hellospringmvc:1.0
